### ISSUE TITLE
刷机及系统包安装问题咨询

### ISSUE THREAD

**Issue by yukaroman** [mmyo456/Yaya-OS#1]
大佬您好，我想请教两个问题。
1. 我之前刷入了恩山上237大佬的固件，改刷您的固件直接选直接升级可以吗，还是要重新刷底包在刷入。
2. 请问这个固件可以安装xl2tpd的系统包么，我发现之前刷入的包安装和内核有关的包都会报如下错误。
![`Y8YK$)Q5 5X{RZJNP~UE}8](https://user-images.githubusercontent.com/65889710/230607325-a1f9d4ba-a6a1-4f29-aa00-637fcd00448e.jpg)

**Comment by mmyo456** [comment]
1,直接升级有风险，建议还是刷底包
2,请检查软件是否支持ARMv8和安装依赖内核

**Comment by yukaroman** [comment]
好的，谢谢
